services:
  - type: web
    name: spacecraft-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
